# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.CharField(max_length=255)),
            ],
        ),
    ]
